image: gcc:6.1

pipelines:
  default:
    - step:
        script:
          - make
          - make test
          - make BUILD_MODE=release
          - make BUILD_MODE=release test
          - make BUILD_MODE=gcov
          - make BUILD_MODE=gcov test